# To be tested
version: "3.7"
services:
    restic-backup:
        container_name: resticBackupProd

        environment:
            RESTIC_REPOSITORY: ${RESTIC_REPOSITORY:?Missing environment variable see readme}
            RESTIC_PASSWORD: ${RESTIC_PASSWORD:?Missing environment variable see readme}

    restic-prune:
        container_name: resticPruneProd

        environment:
            RESTIC_REPOSITORY: ${RESTIC_REPOSITORY:?Missing environment variable see readme}
            RESTIC_PASSWORD: ${RESTIC_PASSWORD:?Missing environment variable see readme}
