version: "3.7"
services:
    restic-backup:
        container_name: resticBackupDev

        depends_on:
            - testrest

        environment:
            RESTIC_REPOSITORY: ${RESTIC_REPOSITORY-rest:http://test:test@testrest:8000}
            RESTIC_PASSWORD: ${RESTIC_PASSWORD-test}

    restic-prune:
        image: mazzolino/restic:1.2

        container_name: resticPruneDev

        depends_on:
            - testrest

        environment:
            RESTIC_REPOSITORY: ${RESTIC_REPOSITORY-rest:http://test:test@testrest:8000}
            RESTIC_PASSWORD: ${RESTIC_PASSWORD-test}

    testrest:
        container_name: testRestDev

        networks:
            - default

        ports:
            - 8000

        volumes:
            - ./.htpasswd:/data/.htpasswd
            - ./testData:/data
