version: "3.7"
services:
    restic-backup:
        container_name: resticBackupProd

    restic-prune:
        container_name: resticPruneProd

    restic-check:
        container_name: resticCheckProd

