version: "3.7"
services:
    restic-backup:
        build:
            context: .

        networks:
            - default

        restart: always

        environment:
            BACKUP_CRON: ${RESTIC_BACKUP_CRON-0 30 3 * * *}
            RUN_ON_STARTUP: ${RESTIC_RUN_ON_STARTUP_BACKUP-true}
            RESTIC_BACKUP_SOURCES: /mnt/volumes
            RESTIC_BACKUP_ARGS: >-
                --tag ${RESTIC_BACKUP_TAG-docker-volumes}
                --verbose
            RESTIC_FORGET_ARGS: >-
                --keep-last ${RESTIC_KEEP_LAST-10}
                --keep-daily ${RESTIC_KEEP_DAILY-7}
                --keep-weekly ${RESTIC_KEEP_WEEKLY-5}
                --keep-monthly ${RESTIC_KEEP_MONTHLY-12}
            TZ: ${RESTIC_TZ-Europe/Berlin}
            RESTIC_REPOSITORY: ${RESTIC_REPOSITORY:?Missing environment variable see readme}
            RESTIC_PASSWORD: ${RESTIC_PASSWORD:?Missing environment variable see readme}
            POST_COMMANDS_SUCCESS: >-
                swaks --to ${NOTIFY_TO:?Missing environment variable see readme}
                --from "${NOTIFY_FROM:?Missing environment variable see readme}"
                --header "Subject: The backup job was executed successfully"
                --body "The backup job was executed successfully"
                --server ${NOTIFY_SERVER:?Missing environment variable see readme}
                --port ${NOTIFY_PORT-587}
                --auth LOGIN
                --auth-user "${NOTIFY_USER:?Missing environment variable see readme}"
                --auth-password "${NOTIFY_PASSWORD:?Missing environment variable see readme}"
                -tls
                || true

            POST_COMMANDS_FAILURE: >-
                swaks --to ${NOTIFY_TO:?Missing environment variable see readme}
                --from "${NOTIFY_FROM:?Missing environment variable see readme}"
                --header "Subject: The backup job has encountered problems"
                --body "The backup job has encountered problems"
                --server ${NOTIFY_SERVER:?Missing environment variable see readme}
                --port ${NOTIFY_PORT-587}
                --auth LOGIN
                --auth-user "${NOTIFY_USER:?Missing environment variable see readme}"
                --auth-password "${NOTIFY_PASSWORD:?Missing environment variable see readme}"
                -tls
                || true

        volumes:
            - /var/lib/docker/volumes:/mnt/volumes:ro

    restic-prune:
        image: mazzolino/restic:1.5

        networks:
            - default

        restart: always

        environment:
            PRUNE_CRON: ${RESTIC_PRUNE_CRON-0 0 4 * * *}
            RUN_ON_STARTUP: ${RESTIC_RUN_ON_STARTUP_PRUNE-false}
            TZ: ${RESTIC_TZ-Europe/Berlin}
            RESTIC_REPOSITORY: ${RESTIC_REPOSITORY:?Missing environment variable see readme}
            RESTIC_PASSWORD: ${RESTIC_PASSWORD:?Missing environment variable see readme}

    restic-check:
        image: mazzolino/restic:1.5

        networks:
            - default

        restart: always

        environment:
            RESTIC_CHECK_ARGS: >-
                --read-data-subset=10%
            CHECK_CRON: ${RESTIC_CHECK_CRON-0 15 5 * * *}
            RUN_ON_STARTUP: ${RESTIC_RUN_ON_STARTUP_CHECK-false}
            TZ: ${RESTIC_TZ-Europe/Berlin}
            RESTIC_REPOSITORY: ${RESTIC_REPOSITORY:?Missing environment variable see readme}
            RESTIC_PASSWORD: ${RESTIC_PASSWORD:?Missing environment variable see readme}
