version: "3.7"
services:
    restic-backup:
        container_name: resticBackupDev

        depends_on:
            - testrest

        environment:
            RESTIC_REPOSITORY: ${RESTIC_REPOSITORY-rest:http://test:test@testrest:8000/test}
            RESTIC_PASSWORD: ${RESTIC_PASSWORD-test}

    restic-prune:
        container_name: resticPruneDev

        depends_on:
            - testrest

        environment:
            RESTIC_REPOSITORY: ${RESTIC_REPOSITORY-rest:http://test:test@testrest:8000/test}
            RESTIC_PASSWORD: ${RESTIC_PASSWORD-test}

    restic-check:
        container_name: resticCheckDev

        depends_on:
            - testrest

        environment:
            RESTIC_REPOSITORY: ${RESTIC_REPOSITORY-rest:http://test:test@testrest:8000/test}
            RESTIC_PASSWORD: ${RESTIC_PASSWORD-test}

    testrest:
        image: restic/rest-server

        container_name: testRestDev

        networks:
            - default

        ports:
            - 8000

        volumes:
            - ./.htpasswd:/data/.htpasswd
            # - ./testData:/data
