version: "3.7"
services:
    restic-backup:
        image: mazzolino/restic:1.5

        networks:
            - default

        restart: always

        environment:
            BACKUP_CRON: ${RESTIC_BACKUP_CRON-"0 30 3 * * *"}
            RUN_ON_STARTUP: ${RESTIC_RUN_ON_STARTUP_BACKUP-0}
            RESTIC_BACKUP_SOURCES: /mnt/volumes
            RESTIC_BACKUP_ARGS: >-
                --tag ${RESTIC_BACKUP_TAG-docker-volumes}
                --verbose
            RESTIC_FORGET_ARGS: >-
                --keep-last ${RESTIC_KEEP_LAST-10}
                --keep-daily ${RESTIC_KEEP_DAILY-7}
                --keep-weekly ${RESTIC_KEEP_WEEKLY-5}
                --keep-monthly ${RESTIC_KEEP_MONTHLY-12}
            TZ: ${RESTIC_TZ-Europe/Berlin}

        volumes:
            - /var/lib/docker/volumes:/mnt/volumes:ro

    restic-prune:
        image: mazzolino/restic:1.5

        networks:
            - default

        restart: always

        environment:
            PRUNE_CRON: ${RESTIC_PRUNE_CRON-"0 0 4 * * *"}
            RUN_ON_STARTUP: ${RESTIC_RUN_ON_STARTUP_PRUNE-1}
            TZ: ${RESTIC_TZ-Europe/Berlin}

    restic-check:
        image: mazzolino/restic:1.5

        networks:
            - default

        restart: always

        environment:
            RESTIC_CHECK_ARGS: >-
                --read-data-subset=10%
            CHECK_CRON: ${RESTIC_CHECK_CRON-"0 15 5 * * *"}
            RUN_ON_STARTUP: ${RESTIC_RUN_ON_STARTUP_CHECK-0}
            TZ: ${RESTIC_TZ-Europe/Berlin}
