# To be tested
version: "3.7"
services:
    restic-backup:
        container_name: resticBackupProd

        environment:
            BACKUP_CRON: "0 30 3 * * *"
            RESTIC_REPOSITORY: rest:<http||https>://<user>:<pass>@<host>:8000 #secure with docker secret
            RESTIC_PASSWORD_FILE: /run/secrets/resticPassword

    restic-prune:
        container_name: resticPruneProd

        environment:
            PRUNE_CRON: "0 0 4 * * *"
            RESTIC_REPOSITORY: rest:<http||https>://<user>:<pass>@<host>:8000 #secure with docker secret. Dockerfile set env on startup
            RESTIC_PASSWORD_FILE: /run/secrets/resticPassword

secrets:
    resticPassword:
        external: true