version: "3.7"
services:
    restic-backup:
        container_name: resticBackupDev

    restic-prune:
        container_name: resticPruneDev

    restic-check:
        container_name: resticCheckDev
